Swallow exit code from OpenFOAM bashrc in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,19 +27,11 @@ jobs:
     - name: Build
       shell: bash
       run: |
-        echo "User: $(whoami)"
-        echo "Home: ${HOME}"
-        echo "~: $(cd ~ && pwd)"
-
         mkdir -p ~/.OpenFOAM
-        ls -A "${HOME}"
-
         cp ./scripts/openfoam-prefs.sh ~/.OpenFOAM/prefs.sh
-        echo "cp ./scripts/openfoam-prefs.sh ~/.OpenFOAM/prefs.sh - OK"
-        ls -A "${HOME}"
 
-        echo "ls -l /opt/openfoam/OpenFOAM-10/etc/bashrc: $(ls -l /opt/openfoam/OpenFOAM-10/etc/bashrc)"
-        . /opt/openfoam/OpenFOAM-10/etc/bashrc
+        # This is just exiting with this message: 'Error: Process completed with exit code 1'
+        . /opt/openfoam/OpenFOAM-10/etc/bashrc || true
 
         echo "FOAM_INST_DIR: ${FOAM_INST_DIR}"
         echo "WM_PROJECT_INST_DIR: ${WM_PROJECT_INST_DIR}"
